import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#131313",
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-variant": "#353535",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1b1b1b",
        "surface-container": "#1f1f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353535",
        "surface-tint": "#ffb5a0",
        "on-surface": "#e2e2e2",
        "on-surface-variant": "#e5beb3",
        "on-background": "#e2e2e2",
        "inverse-surface": "#e2e2e2",
        "inverse-on-surface": "#303030",
        outline: "#ac897f",
        "outline-variant": "#5c4038",
        primary: "#ffb5a0",
        "on-primary": "#601500",
        "primary-container": "#ff5723",
        "on-primary-container": "#541100",
        "inverse-primary": "#b12e00",
        "primary-fixed": "#ffdbd1",
        "primary-fixed-dim": "#ffb5a0",
        "on-primary-fixed": "#3b0900",
        "on-primary-fixed-variant": "#872100",
        secondary: "#a7c8ff",
        "on-secondary": "#003060",
        "secondary-container": "#2e91ff",
        "on-secondary-container": "#002a54",
        "secondary-fixed": "#d5e3ff",
        "secondary-fixed-dim": "#a7c8ff",
        "on-secondary-fixed": "#001c3b",
        "on-secondary-fixed-variant": "#004787",
        tertiary: "#98cbff",
        "on-tertiary": "#003354",
        "tertiary-container": "#0e97ea",
        "on-tertiary-container": "#002c49",
        "tertiary-fixed": "#cee5ff",
        "tertiary-fixed-dim": "#98cbff",
        "on-tertiary-fixed": "#001d33",
        "on-tertiary-fixed-variant": "#004a77",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        xs: "4px",
        sm: "12px",
        md: "20px",
        lg: "32px",
        xl: "48px",
        "margin-mobile": "20px",
        "gutter-mobile": "16px",
      },
      fontFamily: {
        "display-lg": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "headline-lg": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "headline-lg-mobile": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "title-md": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-bold": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "900" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "800" }],
        "title-md": ["20px", { lineHeight: "1.4", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
