-- 21 days of devotional content (verbatim from TRD).
insert into devotionals (day, week, theme, chapter, scripture_ref, scripture_text, reflection_prompt, challenge) values
(1, 1, 'Abide in Christ', 'John 15', 'John 15:1–3',
 'I am the true vine, and my Father is the gardener. He cuts off every branch in me that bears no fruit, while every branch that does bear fruit he prunes so that it will be even more fruitful.',
 'What areas of my life need pruning?',
 'Identify 1 distraction or habit that pulls you away from God and share it with your connect leader via PM.'),
(2, 1, 'Abide in Christ', 'John 15', 'John 15:4–6',
 'Remain in me, as I also remain in you. No branch can bear fruit by itself; it must remain in the vine. Neither can you bear fruit unless you remain in me.',
 'What does "abiding" look like for me daily?',
 'Share a 3 minute voice note prayer to your connect group chat or connect leader.'),
(3, 1, 'Abide in Christ', 'John 15', 'John 15:7–8',
 'If you remain in me and my words remain in you, ask whatever you wish, and it will be done for you. This is to my Father''s glory, that you bear much fruit, showing yourselves to be my disciples.',
 'How is my prayer life connected to abiding?',
 'Write down 3 prayer requests and send it in your connect group chat.'),
(4, 1, 'Abide in Christ', 'John 15', 'John 15:9–11',
 'As the Father has loved me, so have I loved you. Now remain in my love. If you keep my commands, you will remain in my love, just as I have kept my Father''s commands and remain in his love.',
 'Am I obeying from love or obligation?',
 'Set the atmosphere and worship for 5 mins, then spend the next 5 minutes writing down whatever God drops in your heart. Share it with your connect leader or group chat if you feel comfortable.'),
(5, 1, 'Abide in Christ', 'John 15', 'John 15:12–14',
 'My command is this: Love each other as I have loved you. Greater love has no one than this: to lay down one''s life for one''s friends.',
 'How can I love others like Jesus?',
 'Do 1 intentional act of kindness without sharing it to anyone. Let it be between you and Jesus.'),
(6, 1, 'Abide in Christ', 'John 15', 'John 15:15–17',
 'I no longer call you servants… Instead, I have called you friends… You did not choose me, but I chose you and appointed you so that you might go and bear fruit.',
 'What does it mean to be chosen and appointed?',
 'Encourage 1 friend through a prayer, with a voice message, or conversation.'),
(7, 1, 'Abide in Christ', 'John 15', 'John 15:18–27',
 'If the world hates you, keep in mind that it hated me first. If you belonged to the world, it would love you as its own.',
 'How do I stay faithful when my faith is challenged in school?',
 'Share on IG or FB 1 takeaway from camp or this week''s devotion.'),
(8, 2, 'Renewed and Equipped', 'Romans 12', 'Romans 12:1–2',
 'Therefore, I urge you, brothers and sisters, in view of God''s mercy, to offer your bodies as a living sacrifice… Do not conform to the pattern of this world, but be transformed by the renewing of your mind.',
 'Where am I fitting in instead of creating change?',
 'Fast from social media & games and replace that time with prayer or reading.'),
(9, 2, 'Renewed and Equipped', 'Romans 12', 'Romans 12:3–5',
 'For by the grace given me I say to every one of you: Do not think of yourself more highly than you ought… so in Christ we, though many, form one body, and each member belongs to all the others.',
 'How do I view myself in the body of Christ?',
 'Message in your Connect group and ask how you can pray for them. Send a voice note prayer to everyone that responds.'),
(10, 2, 'Renewed and Equipped', 'Romans 12', 'Romans 12:6–8',
 'We have different gifts, according to the grace given to each of us. If your gift is prophesying, then prophesy in accordance with your faith…',
 'What gifts has God given me?',
 'Use your gifts or talents to serve someone today. Take a video or selfie and share it on social media. Tag @favor.youth with #Day10'),
(11, 2, 'Renewed and Equipped', 'Romans 12', 'Romans 12:9–10',
 'Love must be sincere. Hate what is evil; cling to what is good. Be devoted to one another in love. Honor one another above yourselves.',
 'Is my love genuine?',
 'Give sincere encouragement to 3 people via voice note or message.'),
(12, 2, 'Renewed and Equipped', 'Romans 12', 'Romans 12:11–13',
 'Never be lacking in zeal, but keep your spiritual fervor, serving the Lord. Be joyful in hope, patient in affliction, faithful in prayer.',
 'How can I stay spiritually passionate?',
 'Do all the house chores today and tell the person who usually does it that they can rest today.'),
(13, 2, 'Renewed and Equipped', 'Romans 12', 'Romans 12:14–18',
 'Bless those who persecute you; bless and do not curse… If it is possible, as far as it depends on you, live at peace with everyone.',
 'How do I respond to difficult people?',
 'Think of one person who has hurt you. Share that to your connect leader ONLY. Pray together.'),
(14, 2, 'Renewed and Equipped', 'Romans 12', 'Romans 12:19–21',
 'Do not take revenge, my dear friends, but leave room for God''s wrath… Do not be overcome by evil, but overcome evil with good.',
 'How can I overcome evil with good this week?',
 'If something annoying or frustrating happens today, respond with kindness.'),
(15, 3, 'Ready for Battle and Mission', 'Ephesians 6', 'Ephesians 6:1–4',
 'Children, obey your parents in the Lord, for this is right. "Honor your father and mother" — which is the first commandment with a promise.',
 'How do I honor authority well?',
 'Honor your parents/guardians today by writing them a letter or getting a gift. Send and celebrate it in your connect group chats.'),
(16, 3, 'Ready for Battle and Mission', 'Ephesians 6', 'Ephesians 6:5–9',
 'Slaves, obey your earthly masters with respect and fear, and with sincerity of heart, just as you would obey Christ.',
 'How can I serve with excellence at school?',
 'Invite someone to serve someone in your school/community today.'),
(17, 3, 'Ready for Battle and Mission', 'Ephesians 6', 'Ephesians 6:10–13',
 'Finally, be strong in the Lord and in his mighty power. Put on the full armor of God, so that you can take your stand against the devil''s schemes.',
 'Where do I need God''s strength?',
 'Start your morning by praying for strength and protection. Send a 5 minute voice note to your connect group chat.'),
(18, 3, 'Ready for Battle and Mission', 'Ephesians 6', 'Ephesians 6:14–15',
 'Stand firm then, with the belt of truth buckled around your waist, with the breastplate of righteousness in place, and with your feet fitted with the readiness that comes from the gospel of peace.',
 'Am I walking in truth and peace?',
 'Share a bible verse or encouraging message with 1 friend or classmate you are not close to. Send a selfie to your connect group chat.'),
(19, 3, 'Ready for Battle and Mission', 'Ephesians 6', 'Ephesians 6:16–17',
 'In addition to all this, take up the shield of faith… Take the helmet of salvation and the sword of the Spirit, which is the word of God.',
 'Which part of God''s armor do I need most right now?',
 'Memorize this bible verse this week.'),
(20, 3, 'Ready for Battle and Mission', 'Ephesians 6', 'Ephesians 6:18–20',
 'And pray in the Spirit on all occasions with all kinds of prayers and requests… Pray also for me, that whenever I speak, words may be given me so that I will fearlessly make known the mystery of the gospel.',
 'How can I grow in prayer and boldness?',
 'Pray for 3 friends who need Jesus. Take a picture with them and tag them on social media.'),
(21, 3, 'Ready for Battle and Mission', 'Ephesians 6', 'Ephesians 6:21–24',
 'Peace to the brothers and sisters, and love with faith from God the Father and the Lord Jesus Christ. Grace to all who love our Lord Jesus Christ with an undying love.',
 'What will I carry forward after these 21 days?',
 'Invite 1 person who has never come to youth service this Saturday.')
on conflict (day) do update set
  week              = excluded.week,
  theme             = excluded.theme,
  chapter           = excluded.chapter,
  scripture_ref     = excluded.scripture_ref,
  scripture_text    = excluded.scripture_text,
  reflection_prompt = excluded.reflection_prompt,
  challenge         = excluded.challenge;
